## ###################################
## MySQL: mySql, phpMyAdmin
## ###################################

version: '3'
 
services:
  db:
    image: mysql:latest
    container_name: mySql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: myAdmin
    restart: always
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - 8081:80
