## ###################################
## PSQL: postgreSQL, pgAdmin 4
## ###################################
## Current System is setup for MySql
## Changes have to be done manually
##  > Environment:
##      > env-start.ps1
##      > env-end.ps1
##  > Backend:
##      > Implement PSQL in Laravel Environment
##      > See Laravel Doks
## ####################################

version: "3"

services:
  postgres:
    image: postgres:12.3-alpine
    restart: always
    environment:
        POSTGRES_PASSWORD: root
        POSTGRES_USER: admin
    volumes:
        - postgres:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: root
        PGADMIN_LISTEN_PORT: 80
    ports:
        - 15432:80
    volumes:
        - pgadmin:/var/lib/pgadmin
    depends_on:
        - postgres

volumes:
    postgres:
    pgadmin: